# v2 syntax
version: '2'

# Named volumes
volumes:
  # MySQL Data
  my-team-pubg-mysql-data:
    driver: local

services:
  # MySQL (5.7)
  mysql:
    image: mysql:5.7
    container_name: my-team-mysql
    volumes:
      - ../mysql/data/:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=myteam
      - MYSQL_USER=myteampubg
      - MYSQL_PASSWORD=myteampubg
      - MYSQL_ROOT_PASSWORD=myteampubg

  # PHP (with Caddy)
  app:
    image: ambientum/php:7.1-caddy
    container_name: my-team-pubg
    volumes:
      - ../:/var/www/app
    ports:
      - "80:8080"
    links:
      - mysql